apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o9ah2085w-nodejs
  janus-idp.io/tekton: o9ah2085w-nodejs
  backstage.io/kubernetes-id: o9ah2085w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o9ah2085w-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
